[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = []

[tasks.test-with-cpu]
command = "cargo"
args = ["test", "--release", "--no-default-features", "--features", ""]
dependencies = []

[tasks.test-with-cuda]
command = "cargo"
# In NeuralMachine, we use 16 device streams. so 4 * 64 = 64. If we use more, we get a panic.
args = ["test", "--release", "--no-default-features", "--features", "cuda", "--", "--test-threads", "4"]
dependencies = []

[tasks.my-flow]
dependencies = [
    "format",
    "test-with-cpu",
    "test-with-cuda",
]
