[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = []

[tasks.test-with-cpu]
command = "cargo"
args = ["test", "--release", "--no-default-features", "--features", "", "--", "--test-threads", "1"]
dependencies = []

[tasks.test-with-cuda]
command = "cargo"
# In NeuralMachine, we use 16 device streams. so we use 1 test threads. If we use more, we get a panic.
# It's because a NVIDIA GeForce RTX 4060 has 8 GB VRAM.
args = ["test", "--release", "--no-default-features", "--features", "cuda", "--", "--test-threads", "1"]
dependencies = []

[tasks.my-flow]
dependencies = [
    "format",
    "test-with-cpu",
    "test-with-cuda",
]
