mod training;
pub use training::*;
mod models;
pub mod tensor;
pub use models::*;
mod devices;
pub use devices::*;
mod operators;
pub use operators::*;
mod tokenizers;
pub use tokenizers::*;
mod neural_machine;
pub use neural_machine::*;
pub use optimizers::*;
pub mod graph_theory;
mod optimizers;
const EPSILON: f32 = 1e-8;
